# Site settings
title: Uzziel Perez
description: Uzziel Perez GitHub Page
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: http://uzzieparticlez.github.io
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br


# User settings
username: Uzziel Perez
user_description: Novice Particle Hunter. Open Science Advocate. Football Nerd and Science Toys Collector.
user_title: High Energy Physics PhD student
email: cperez3@crimson.ua.edu
twitter_username: Uzziesh
github_username:  uzzielperez
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
